import "@/app/globals.css"
import 'bootstrap/dist/css/bootstrap.min.css';
import '@/app/css/common.css'
export const metadata = {
	title       : "Dreamer",
	description : "Generated by create next app",
};

export default function RootLayout( { children } ) {
	return (
		<html lang="en">
			<body>
				<main>
					{ children }
				</main>
			</body>
		</html>
	);
}
